config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get '/addagroupbymalin123123', to: 'fbgroups#new'
  resources :fbgroups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fbgroup.rb
class Fbgroup < ApplicationRecord

        
    geocoded_by :name,
        :latitude => :lat, :longitude => :long
        after_validation :geocode
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fbgroups_controller.rb
class FbgroupsController < ApplicationController

    def new
        @fbgroup = Fbgroup.new()
        @fbgroups = Fbgroup.all

    end
    
    def edit
        @fbgroup = Fbgroup.find(params[:id])
        @fbgroups = Fbgroup.all
    end

    def update
        @fbgroup = Fbgroup.find(params[:id])
        @fbgroup.update(fbgroup_params)
        redirect_to root_url
    end

    def create
        @fbgroup = Fbgroup.new(fbgroup_params)
        @fbgroup.save
        redirect_to root_url
    end

    def destroy
    end

    private

    def fbgroup_params
        params.require(:fbgroup).permit(:name, :url, :adminemail, :lat, :long)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        fbgroups = Fbgroup.all
        @fbmarkers = fbgroups.map do |group|
            {
                latlng: [group[:lat], group[:long]],
                popup: "
                <div>
                <header>
                <h6>#{group[:name]}</h6>
                </header>
                <a href='http://#{group[:url]}' target='_blank'>Gå till Facebook</a>
                </div>"
            }
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fbgroups_helper.rb
module FbgroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fbgroups/edit.html.erb
<div class="row">
    <div class="col-md-6">
    <h1>Lägg till en grupp!</h1>
        <%= form_for @fbgroup do |f| %>
            <div class="form-group">
                <%= f.text_field :name, :placeholder => "Stad", :class => "form-control" %>
            </div>
            <div class="form-group">
                <%= f.text_field :url, :placeholder => "Länk till FB-Grupp", :class => "form-control" %>
            </div>
            <div class="form-group">
            <%= f.text_field :adminemail, :placeholder => "Admin email", :class => "form-control" %>
            </div>
            <div class="form-group">
            <%= f.number_field :lat, step: :any, :placeholder => "Latitude", :class => "form-control" %>
            </div>
            <div class="form-group">
            <%= f.number_field :long, step: :any, :placeholder => "Longitude", :class => "form-control" %>
            </div>
            <%= f.submit "Spara Grupp" %>
        <% end %>
    </div>
    <div class="col-md-12">
    <h1>Nuvarande grupper</h1>
        <table class="table">
            <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ort</th>
                    <th scope="col">URL</th>
                    <th scope="col">Adminemail</th>
                </tr>
            </thead>
            <tbody>
                <% @fbgroups.each do |group| %>
                    <tr>
                        <th scope="row"><%= group.id %></th>
                        <td><%= group.name %></td>
                        <td><%= group.url %></td>
                        <td><%= group.adminemail %></td>
                        <td><%= link_to "Ändra", edit_fbgroup_url(group.id) %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/fbgroups/new.html.erb
<div class="row">
    <div class="col-md-6">
    <h1>Lägg till en grupp!</h1>
        <%= form_for @fbgroup do |f| %>
            <div class="form-group">
                <%= f.text_field :name, :placeholder => "Stad", :class => "form-control" %>
            </div>
            <div class="form-group">
                <%= f.text_field :url, :placeholder => "Länk till FB-Grupp", :class => "form-control" %>
            </div>
            <div class="form-group">
            <%= f.text_field :adminemail, :placeholder => "Admin email", :class => "form-control" %>
            </div>
            <div class="form-group">
            <%= f.number_field :lat, step: :any, :placeholder => "Latitude", :class => "form-control" %>
            </div>
            <div class="form-group">
            <%= f.number_field :long, step: :any, :placeholder => "Longitude", :class => "form-control" %>
            </div>
            <%= f.submit "Spara Grupp" %>
        <% end %>
    </div>
    <div class="col-md-12">
    <h1>Nuvarande grupper</h1>
        <table class="table">
            <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ort</th>
                    <th scope="col">URL</th>
                    <th scope="col">Adminemail</th>
                </tr>
            </thead>
            <tbody>
                <% @fbgroups.each do |group| %>
                    <tr>
                        <th scope="row"><%= group.id %></th>
                        <td><%= group.name %></td>
                        <td><%= group.url %></td>
                        <td><%= group.adminemail %></td>
                        <td><%= link_to "Ändra", edit_fbgroup_url(group.id) %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/home/index.html.erb
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-3">
    <h1>Välkommen till Hjälpkontakt</h1>
    <p>Här listar vi alla grupper som finns på Facebook för att hjälpa folk som tillhör riskgrupper.
    Klicka på en bubbla på kartan och sen länken för att komma in till deras Facebookgrupp.</p>
</div>
<div class="col-xs-12 col-sm-12 col-md-9">
<%= map(:center => {
    :latlng => [62.2229515, 15.0043013],
    :zoom => 5
  },
  :markers => @fbmarkers
) %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hjalpkontakt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""/>
  <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>